{application,umicp,
             [{applications,[kernel,stdlib,elixir,logger,crypto,jason,mint,
                             mint_web_socket,finch,excoveralls]},
              {description,"UMICP Elixir bindings for high-performance communication and matrix operations\nwith native type support and MCP-compatible tool discovery.\n"},
              {modules,['Elixir.Jason.Encoder.UMICP.Envelope','Elixir.UMICP',
                        'Elixir.UMICP.Discovery.DiscoverableService',
                        'Elixir.UMICP.Discovery.OperationSchema',
                        'Elixir.UMICP.Discovery.ServerInfo',
                        'Elixir.UMICP.Envelope','Elixir.UMICP.Error',
                        'Elixir.UMICP.Matrix.Operations',
                        'Elixir.UMICP.OperationType',
                        'Elixir.UMICP.Transport.HTTP2',
                        'Elixir.UMICP.Transport.WebSocket']},
              {registered,[]},
              {vsn,"0.2.2"}]}.
