{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hivellm.org",
    "module": "umicp-kotlin",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "umicp-kotlin-0.1.3.jar",
          "url": "umicp-kotlin-0.1.3.jar",
          "size": 295367,
          "sha512": "e51ede7a9391bd953a9439af554377ed24d27a4c87c9627eaf01f8d23eaf34c7b02cfbdc5d1a971d740c27e1851b617c53b38ea326258bfe42e22ca06330ecae",
          "sha256": "bdce8dda0d6caa837cd3c8a3c378d1c101f14618602043b8e740512dca0282f7",
          "sha1": "5ff5c206ca69f4dd0a669fe2b1790e3b1648eb3d",
          "md5": "e5e803fe2259f0d7a1260e578924ac58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.java-websocket",
          "module": "Java-WebSocket",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-sse",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.lz4",
          "module": "lz4-java",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.4.14"
          }
        }
      ],
      "files": [
        {
          "name": "umicp-kotlin-0.1.3.jar",
          "url": "umicp-kotlin-0.1.3.jar",
          "size": 295367,
          "sha512": "e51ede7a9391bd953a9439af554377ed24d27a4c87c9627eaf01f8d23eaf34c7b02cfbdc5d1a971d740c27e1851b617c53b38ea326258bfe42e22ca06330ecae",
          "sha256": "bdce8dda0d6caa837cd3c8a3c378d1c101f14618602043b8e740512dca0282f7",
          "sha1": "5ff5c206ca69f4dd0a669fe2b1790e3b1648eb3d",
          "md5": "e5e803fe2259f0d7a1260e578924ac58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "umicp-kotlin-0.1.3-sources.jar",
          "url": "umicp-kotlin-0.1.3-sources.jar",
          "size": 30967,
          "sha512": "0e77f6597bc95f2f4a2361e34b8c923ffcb9f3ceab3d7259eb3b17d84fd7958c9cf998072842f67815aee0cbc1b96bc9936cd82bfafd4db1a4a8b5e5ca575ea1",
          "sha256": "1a6f4c23666cdcff9af90fa7e8384fc7cc40ac723c2e73902eb1caafa74c29f1",
          "sha1": "0dc948f010d1bdf18e658263938360e3326abdc6",
          "md5": "ba7dde0a91a039260b4b148288481d5e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "umicp-kotlin-0.1.3-javadoc.jar",
          "url": "umicp-kotlin-0.1.3-javadoc.jar",
          "size": 261,
          "sha512": "a602602a1ae942a7b6ca4bf33eac5f6b7de3f16f189ec5cf93eeda8962d9063d7e02cb14fcf0504ff5be6df42e50147b2cb790c378d9333b752b913c184c8b6f",
          "sha256": "f848b2e6a406250b5ae42e3a14082de3fc4c46ad8835fd6c19b29d128188f23b",
          "sha1": "93a6877e54e4144cb411e99bbd4a1bf21eb59ead",
          "md5": "ae18e8ff8b0a6528d92dc3cb9f1f22fc"
        }
      ]
    }
  ]
}
